-- This should act like an index.html file that just includes other files
-- Currently it does not include autobraces.lua because it is a WIP and I dont want it breaking my nvim
--
-- This is in an autoload folder because I intend for autobraces to be a plugin. That is why it is not in the lua/elwyn folder (this is for all my hacky config)
